name: SillyEnchants
version: '1.0-SNAPSHOT'
main: io.github.lamelemon.sillyEnchants.SillyEnchants
api-version: '1.21.8'
authors: [ lamius lemonius ]
description: Adds custom enchantments
website: https://youtu.be/dQw4w9WgXcQ
